# Generated by Django 3.1.2 on 2020-11-01 21:11

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human readable account name (like "Coca Cola")', max_length=128)),
                ('details', jsonfield.fields.JSONField(help_text='JSON-encoded content', max_length=102400)),
            ],
        ),
    ]
